version: '3.8'

services:
  front:
    build:
      context: ./apps/front
      target: builder
    env_file: ./apps/front/.env.production
    networks:
      - sagdashboard
    expose:
      - "5173"

networks:
  sagdashboard:
    driver: bridge
