version: '3.8'

services:
  front:
    build:
      context: ./apps/front
      target: builder
    env_file: ./apps/front/.env.production
    networks:
      - sagdashboard
    expose:
      - "5173"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashsag.rule=Host(`dashsag.sagzap.com.br`)"
      - "traefik.http.routers.dashsag.entrypoints=websecure"
      - "traefik.http.routers.dashsag.tls=true"
      - "traefik.http.routers.dashsag.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.dashsag.loadbalancer.server.port=5173"

networks:
  sagdashboard:
    driver: bridge
